version: "3.4"
services:
  selenium:
    image: "selenium/standalone-chrome"
    container_name: selenium
    shm_size: 2g
    ports:
      - "4444"
    networks:
      - selenium
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 30s
      timeout: 10s
      retries: 5 

  e2e:
    image: e2e-test
    build: .
    environment: 
      - PASSWORD=${PASSWORD}
    depends_on:
      selenium:
        condition: service_healthy  
    links:
      - selenium  
    networks:
      - selenium
    volumes:
      - ./allure-results:/app/allure-results
  allure:
    image: "frankescobar/allure-docker-service"
    ports:
      - "5050:5050"
    depends_on:
      - selenium
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/default-reports
networks:
  selenium:
    name: selenium