version: "3.4"
services:
  selenium:
    image: "selenium/standalone-chrome"
    container_name: selenium
    shm_size: 2g
    ports:
      - "4444"
    networks:
      - selenium

  e2e:
    image: e2e-test
    build: .
    environment: 
      - PASSWORD=${PASSWORD}
    depends_on:
      - selenium
    links:
      - selenium
    networks:
      - selenium
    volumes:
      - "./allure-results:/app/allure-results"

networks:
  selenium:
    name: selenium